<?php

namespace Esprit\TrocBundle\Repository;

/**
 * EchangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EchangeRepository extends \Doctrine\ORM\EntityRepository
{
}
