<?php

namespace Esprit\TrocBundle\Repository;
use AppBundle\Entity\User;
use Esprit\TrocBundle\Entity\Echange;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function countSommeVote(User $user)
    {
        return $this->createQueryBuilder('v')
            ->andWhere('v.idUser = :user')
            ->setParameter('user', $user)
            ->select('SUM(v.vote) as votes')
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function countVote(User $user)
    {
        return $this->createQueryBuilder('v')
            ->andWhere('v.idUser = :user')
            ->setParameter('user', $user)
            ->select('count(v.id) as vo')
            ->getQuery()
            ->getOneOrNullResult();
    }
}
